spring:
    application:
        name: "Arquitetura Spring"
    jpa:
        show-sql: true
    main:
      lazy-initialization: false
app:
    config:
        variavel: "valor da variável X"
        valor1: 500